"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını yükle (Varsa ortam değişkenlerini yükler)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-qat@c!_c=*g)d7*zp&ln=+3=$am*e=kt&q1zjqfw=z1og$#w*8"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "")
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["*"] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI / WebSocket desteği için en başta olmalıdır
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Uygulamalar:
    'tickets', 
    'captcha',
    'channels',  # Django Channels (WebSockets)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "tickets.middleware.CustomErrorPageMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'], # Buradaki DIRS listesine bunu ekliyoruz
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'tickets.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Django Channels Katmanı (WebSocket İletişimi)
# Yerel geliştirme / test ortamında InMemory, canlıda REDIS_URL tanımlanmışsa Redis kullanılır.
redis_url = os.environ.get("REDIS_URL")
if redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [redis_url],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Caches Configuration (12-Factor App: Canlıda Redis, Geliştirmede Yerel Bellek)
# Canlı ortamda çoklu worker'lar arasında hız limitlerinin ve oturum kilitlemelerinin senkronize çalışmasını sağlar.
if redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": redis_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-support-tickets",
        }
    }



# Database (12-Factor App: PostgreSQL / SQLite Çift Uyumluluk)
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Canlı ortamda DATABASE_URL veya POSTGRES_DB ortam değişkeni tanımlıysa PostgreSQL kullanılır.
# Tanımlı değilse yerel geliştirme için SQLite (db.sqlite3) kullanılır.
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "tr-tr" # dil Türkçeye ç

TIME_ZONE = "Europe/Istanbul" # saat dilimi 

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]


# Email Konfigürasyonu (12-Factor: Canlıda SMTP, Geliştirmede Console)
# https://docs.djangoproject.com/en/stable/topics/email/#topic-email-configuration
_email_host = os.environ.get('EMAIL_HOST', '')
if _email_host:
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@desteksistemi.com')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@desteksistemi.com')


# Kullanıcı oturumu açık değilse yönlendirilecek varsayılan giriş URL'i
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'ticket_list'
LOGOUT_REDIRECT_URL = 'login'

"""
LOGIN_URL = 'login':

Normalde: Django'da @login_required ile korunan bir sayfaya anonim biri girmeye çalıştığında sistem onu otomatik olarak varsayılan /accounts/login/ rotasına yönlendirir.

Bizim Projemizde: Bizim giriş rotamız tickets/urls.py içinde name='login' (yani /login/) olarak tanımlandı. Bu ayar sayesinde Django 404 hatası vermek yerine kullanıcıyı doğrudan bizim hazırladığımız /login/ sayfasına postalar (Örn: /login/?next=/ticket/1/edit/).

LOGIN_REDIRECT_URL = 'ticket_list':

Kullanıcı giriş yaptıktan sonra hedef bir sayfa belirtilmemişse (?next=... parametresi yoksa) varsayılan olarak ana talep listesine (/) yönlendirilir.

LOGOUT_REDIRECT_URL = 'login':

Kullanıcı üst menüden "Çıkış Yap" butonuna bastığında oturumu kapatılır ve otomatik olarak tekrar giriş sayfasına (/login/) yönlendirilir.
"""


# Media Files (Kullanıcı Yüklemeleri)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

'''
MEDIA_ROOT yüklenen dosyaların bilgisayarınızda saklanacağı fiziksel klasörü, 
MEDIA_URL ise bu dosyalara tarayıcıdan hangi web adresiyle erişileceğini belirtir.
'''


# ==============================================================================
# Üretim (Production) Güvenlik Başlıkları ve CSRF Ayarları
# ==============================================================================
_csrf_trusted = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted.split(",") if origin.strip()]

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000  # 1 Yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    if os.environ.get("SECURE_SSL_REDIRECT", "False").lower() in ("true", "1", "yes"):
        SECURE_SSL_REDIRECT = True

# ==============================================================================
# Oturum Yönetimi ve Güvenliği (Session Management & Expiry)
# ==============================================================================
# Oturum çerezi süresi: 8 saat (28800 saniye). Kurumsal güvenlik gereği oturumların süresiz kalmasını sınırlar.
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", 28800))
# Tarayıcı tamamen kapatıldığında oturumu otomatik sonlandır
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get("SESSION_EXPIRE_AT_BROWSER_CLOSE", "True").lower() in ("true", "1", "yes")
# Kullanıcı her aktif işlem yaptığında oturum süresini kaydırarak yenile (Sliding session)
SESSION_SAVE_EVERY_REQUEST = True
# Oturum çerezini JavaScript erişimine kapat (XSS ile çerez hırsızlığını engeller)
SESSION_COOKIE_HTTPONLY = True


# ==============================================================================
# Merkezi Loglama (Logging) Konfigürasyonu
# ==============================================================================
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file_errors": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django_errors.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "standard",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_errors"],
            "level": "INFO",
            "propagate": False,
        },
        "tickets": {
            "handlers": ["console", "file_errors"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ==============================================================================
# Harici Webhook & AI Copilot Entegrasyonları
# ==============================================================================
# Slack / Discord / Teams acil talep bildirim webhook URL'si (Boş bırakılırsa sessizce atlar)
OUTGOING_WEBHOOK_URL = os.getenv("OUTGOING_WEBHOOK_URL", "")

# AI Copilot (İsteğe bağlı OpenAI / LLM API anahtarı; boşsa yerel akıllı kural motoru çalışır)
AI_COPILOT_API_KEY = os.getenv("AI_COPILOT_API_KEY", "")

# Gelen e-posta ile bilet cevaplama webhook güvenlik anahtarı
INBOUND_EMAIL_WEBHOOK_SECRET = os.getenv("INBOUND_EMAIL_WEBHOOK_SECRET", "") or SECRET_KEY[:32]




