# Generated by Django 6.1 on 2026-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_ticket_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcomment",
            name="is_internal",
            field=models.BooleanField(
                default=False, verbose_name="İç Not (Sadece Yöneticiler Görsün)"
            ),
        ),
    ]
