# Generated by Django 6.1 on 2026-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ticket_attachments/%Y/%m/%d/",
                verbose_name="Dosya / Görsel Eki",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comment_attachments/%Y/%m/%d/",
                verbose_name="Dosya / Görsel Eki",
            ),
        ),
    ]
