# Generated by Django 6.1 on 2026-09-09 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0007_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Grup Adı")),
                (
                    "is_general",
                    models.BooleanField(
                        default=False, verbose_name="Genel Ekip Odası Mı?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Yönetici",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="chat_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Grup Üyeleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sohbet Grubu",
                "verbose_name_plural": "Sohbet Grupları",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Mesaj İçeriği")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tickets.chatgroup",
                        verbose_name="İlişkili Grup",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alıcı (Özel Mesaj)",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sohbet Mesajı",
                "verbose_name_plural": "Sohbet Mesajları",
                "ordering": ["created_at"],
            },
        ),
    ]
