# Generated by Django 6.1 on 2026-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0008_chatgroup_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="İşaretlenirse tüm kullanıcılar bu talebi ve çözümünü görebilir. İşaretlenmezse sadece yöneticiler görebilir.",
                verbose_name="Herkese Açık (Topluluk / Forum Talebi)",
            ),
        ),
    ]
