# Generated by Django 6.1 on 2026-09-10 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0009_ticket_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcomment",
            name="is_solution",
            field=models.BooleanField(
                default=False, verbose_name="En İyi Yanıt / Çözüm"
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Beğenen Kullanıcılar",
            ),
        ),
    ]
