# Generated by Django 6.1 on 2026-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0010_ticketcomment_is_solution_ticketcomment_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="İşaretlenirse tüm kullanıcılar bu talebi ve çözümünü görebilir. İşaretlenmezse sadece yöneticiler görebilir.",
                verbose_name="Herkese Açık (Topluluk / Forum Talebi)",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Düşük"),
                    ("medium", "Orta"),
                    ("high", "Yüksek"),
                    ("urgent", "Acil"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
                verbose_name="Öncelik",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Açık"),
                    ("in_progress", "Devam Ediyor"),
                    ("resolved", "Çözüldü"),
                    ("closed", "Kapalı"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Tarih"
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="is_solution",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="En İyi Yanıt / Çözüm"
            ),
        ),
    ]
