# Generated by Django 6.1 on 2026-09-10 18:25

import django.db.models.deletion
import tickets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0011_alter_ticket_is_public_alter_ticket_priority_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ticket_attachments/%Y/%m/%d/",
                validators=[tickets.validators.validate_file_security],
                verbose_name="Dosya / Görsel Eki",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comment_attachments/%Y/%m/%d/",
                validators=[tickets.validators.validate_file_security],
                verbose_name="Dosya / Görsel Eki",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Süper Yönetici"),
                            ("support_agent", "Teknik Destek Uzmanı"),
                            ("finance_agent", "Finans Yetkilisi"),
                            ("user", "Standart Kullanıcı"),
                        ],
                        default="user",
                        max_length=30,
                        verbose_name="Kullanıcı Rolü",
                    ),
                ),
                (
                    "assigned_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Teknik Destek veya Finans yetkilileri için sorumlu oldukları departman/kategorileri seçiniz.",
                        related_name="assigned_staff",
                        to="tickets.category",
                        verbose_name="Sorumlu Olduğu Kategoriler",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili ve Rolü",
                "verbose_name_plural": "Kullanıcı Profilleri ve Rolleri",
            },
        ),
    ]
