# Generated by Django 6.1 on 2026-09-10 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0012_alter_ticket_attachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Makale Başlığı"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Genel Bilgiler"),
                            ("account", "Hesap & Güvenlik"),
                            ("billing", "Faturalandırma & Ödeme"),
                            ("technical", "Teknik Sorunlar & Hatalar"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                ("content", models.TextField(verbose_name="Makale İçeriği")),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Arama eşleştirmesi için anahtar kelimeler (virgülle ayırın)",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Görüntülenme Sayısı"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayında mı?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilgi Bankası Makalesi",
                "verbose_name_plural": "Bilgi Bankası Makaleleri",
                "ordering": ["-views_count", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Destek yetkilisi tarafından ilk yanıtın verildiği zaman.",
                null=True,
                verbose_name="İlk Yanıt Tarihi",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Süper Yönetici"),
                    ("support_agent", "Teknik Destek Uzmanı"),
                    ("finance_agent", "Finans Destek Uzmanı"),
                    ("user", "Standart Kullanıcı"),
                ],
                default="user",
                max_length=30,
                verbose_name="Kullanıcı Rolü",
            ),
        ),
        migrations.CreateModel(
            name="TicketRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ - Çok Memnun Kaldım (5/5)"),
                            (4, "⭐⭐⭐⭐ - Memnun Kaldım (4/5)"),
                            (3, "⭐⭐⭐ - Orta (3/5)"),
                            (2, "⭐⭐ - Memnun Kalmadım (2/5)"),
                            (1, "⭐ - Hiç Memnun Kalmadım (1/5)"),
                        ],
                        verbose_name="Memnuniyet Puanı",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="Görüş ve Öneriler"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Değerlendirme Tarihi"
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="tickets.ticket",
                        verbose_name="Destek Talebi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Değerlendiren Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talep Memnuniyet Değerlendirmesi",
                "verbose_name_plural": "Talep Memnuniyet Değerlendirmeleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
