# Generated by Django 6.1 on 2026-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0013_knowledgebasearticle_ticket_first_response_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
