# Generated by Django 6.1 on 2026-09-11 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0014_emailverification_failed_attempts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="sla_deadline",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="SLA hedef teslim / ilk yanıt tarihi.",
                null=True,
                verbose_name="SLA Son Tarihi",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Tarih"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Okundu Mu?"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="tickets_not_recipie_a596ee_idx"
            ),
        ),
    ]
