# Generated by Django 6.1 on 2026-09-11 09:57

import django.db.models.deletion
from django.db import migrations, models

def map_categories(apps, schema_editor):
    Category = apps.get_model("tickets", "Category")
    KnowledgeBaseArticle = apps.get_model("tickets", "KnowledgeBaseArticle")
    cat_general = Category.objects.filter(name__icontains="Genel").first()
    cat_account = Category.objects.filter(name__icontains="Hesap").first()
    cat_billing = Category.objects.filter(name__icontains="deme").first() or Category.objects.filter(name__icontains="Ödeme").first()
    cat_tech = Category.objects.filter(name__icontains="Teknik").first()

    for article in KnowledgeBaseArticle.objects.all():
        t = (article.title or '').lower()
        if 'ifre' in t or 'sifre' in t or 'hesap' in t:
            article.category = cat_account or cat_general
        elif 'fatura' in t or 'deme' in t:
            article.category = cat_billing or cat_general
        elif 'dosya' in t or 'ekran' in t:
            article.category = cat_general
        elif 'sayfa' in t or 'hata' in t or 'ba' in t:
            article.category = cat_tech or cat_general
        else:
            article.category = cat_general
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0015_ticket_sla_deadline_alter_chatmessage_created_at_and_more"),
    ]

    operations = [
        migrations.RunSQL("UPDATE tickets_knowledgebasearticle SET category = 1;"),
        migrations.AlterField(
            model_name="knowledgebasearticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kb_articles",
                to="tickets.category",
                verbose_name="Kategori",
            ),
        ),
        migrations.RunPython(map_categories, migrations.RunPython.noop),
    ]
