# Generated by Django 6.1 on 2026-09-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0016_alter_knowledgebasearticle_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Aktif mi?"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_secret",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="2FA TOTP Gizli Anahtarı",
            ),
        ),
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Şablon Başlığı"),
                ),
                ("content", models.TextField(verbose_name="Yanıt Metni")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Belirli bir kategoriye özel şablon için seçin veya tüm taleplerde geçerli olması için boş bırakın.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canned_responses",
                        to="tickets.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazır Yanıt Şablonu",
                "verbose_name_plural": "Hazır Yanıt Şablonları",
                "ordering": ["title"],
            },
        ),
    ]
