# Generated by Django 6.1 on 2026-09-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0017_userprofile_is_2fa_enabled_userprofile_totp_secret_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan Kullanıcı",
            ),
        ),
    ]
