# Generated by Django 6.1 on 2026-09-11 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0018_alter_ticket_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "recipient", "created_at"],
                name="tickets_cha_sender__93695f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["group", "created_at"], name="tickets_cha_group_i_54587e_idx"
            ),
        ),
    ]
