# Generated by Django 6.1 on 2026-09-11 14:12

import tickets.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0019_chatmessage_tickets_cha_sender__93695f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/%Y/%m/",
                validators=[tickets.validators.validate_file_security],
                verbose_name="Profil Fotoğrafı",
            ),
        ),
    ]
