# Generated by Django 6.1 on 2026-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0020_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcomment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
    ]
