# Generated by Django 6.1 on 2026-09-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0021_ticketcomment_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Etiket Adı"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Örn: #2563eb, #dc2626, #16a34a, #d97706, #9333ea",
                        max_length=20,
                        verbose_name="Renk Kodu",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Talep Etiketi",
                "verbose_name_plural": "Talep Etiketleri",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Eğer bu talep mükerrer ise ve başka bir ana talep ile birleştirildiyse referans verir.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_tickets",
                to="tickets.ticket",
                verbose_name="Birleştirilen Ana Talep",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets",
                to="tickets.tickettag",
                verbose_name="Etiketler",
            ),
        ),
    ]
