# Generated by Django 6.1 on 2026-09-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0022_tickettag_ticket_merged_into_ticket_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="starred_chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favorileyenler",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_edited",
            field=models.BooleanField(default=False, verbose_name="Düzenlendi mi?"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Eğer bu talep yinelenen ise ve başka bir ana talep ile birleştirildiyse referans verir.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_tickets",
                to="tickets.ticket",
                verbose_name="Birleştirilen Ana Talep",
            ),
        ),
        migrations.CreateModel(
            name="UserChatPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Arşivlendi mi?"),
                ),
                (
                    "cleared_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sohbet Temizleme Tarihi"
                    ),
                ),
                (
                    "dm_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_chat_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="tickets.chatgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Sohbet Tercihi",
                "verbose_name_plural": "Kullanıcı Sohbet Tercihleri",
                "unique_together": {("user", "dm_user"), ("user", "group")},
            },
        ),
    ]
