# Generated by Django 6.1 on 2026-09-12 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0023_chatmessage_favorited_by_chatmessage_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_for_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="hidden_chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bu Kullanıcıdan Gizlendi",
            ),
        ),
    ]
