# Generated by Django 6.1 on 2026-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0024_chatmessage_deleted_for_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
    ]
