# Generated by Django 6.1 on 2026-09-14 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0025_chatmessage_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cannedresponse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canned_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AlterField(
            model_name="ticketrating",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Değerlendiren Kullanıcı",
            ),
        ),
    ]
